"use client";

import { useState, useRef } from "react";
import { SearchForm } from "@/components/SearchForm";
import { ResultsList } from "@/components/ResultsList";
import { LeadDetail } from "@/components/LeadDetail";
import { Lead, SearchParams } from "@/types";
import { Sparkles, ChevronRight } from "lucide-react";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { GoogleGenAI } from "@google/genai";
import { COUNTRIES } from "@/lib/constants";
import { useLanguage } from "@/contexts/LanguageContext";

export default function Home() {
  const { t } = useLanguage();
  const [step, setStep] = useState<"search" | "results" | "detail">("search");
  const [searchParams, setSearchParams] = useState<SearchParams | null>(null);
  const [results, setResults] = useState<Lead[]>([]);
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const reportCache = useRef<Map<string, string>>(new Map());

  const handleSearch = async (params: SearchParams) => {
    setIsLoading(true);
    setError(null);
    setSearchParams(params);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.NEXT_PUBLIC_GEMINI_API_KEY });
      const { icp, service, country, state, city } = params;

      const countryData = COUNTRIES.find((c) => c.value === country);
      const countryLabel = countryData?.label ?? country;
      const language = countryData?.language ?? "pt-BR";

      const locationParts = [city, state, countryLabel].filter(Boolean);
      const locationStr = locationParts.join(", ");

      const languageInstructions: Record<string, string> = {
        "pt-BR": "Responda SEMPRE em português do Brasil (pt-BR).",
        "pt-PT": "Responda SEMPRE em português europeu (pt-PT).",
        es: "Responda SIEMPRE en español.",
        en: "ALWAYS respond in English.",
      };
      const languageInstruction =
        languageInstructions[language] ?? languageInstructions["pt-BR"];

      const aiSummaryInstructions: Record<string, string> = {
        "pt-BR":
          "Resumo de oportunidade de no máximo 3 linhas em português (pt-BR), explicando por que este negócio é um bom lead para o serviço oferecido.",
        "pt-PT":
          "Resumo de oportunidade de no máximo 3 linhas em português europeu (pt-PT), explicando por que este negócio é um bom lead para o serviço oferecido.",
        es: "Resumen de oportunidad de máximo 3 líneas en español, explicando por qué este negocio es un buen lead para el servicio ofrecido.",
        en: "Opportunity summary of maximum 3 lines in English, explaining why this business is a good lead for the offered service.",
      };
      const aiSummaryInstruction =
        aiSummaryInstructions[language] ?? aiSummaryInstructions["pt-BR"];

      const prompt = `
        ${languageInstruction}
        You are a B2B prospecting expert.
        The user is looking for leads with the following Ideal Customer Profile (ICP): "${icp}".
        The target location is: "${locationStr}".
        The user offers the following service: "${service}".

        Use Google Maps to find around 10 to 15 real businesses that match this ICP in this location.

        For each business found, provide the following data in strict JSON format (an array of objects):
        [
          {
            "id": "a unique identifier generated by you",
            "name": "Business name",
            "address": "Full address",
            "city": "City",
            "state": "State",
            "country": "${country}",
            "rating": 4.5,
            "userRatingCount": 120,
            "primaryType": "Main category",
            "nationalPhoneNumber": "Phone if available, or null",
            "websiteUri": "Website if available, or null",
            "googleMapsUri": "Google Maps link if available, or null",
            "digitalPainScore": a number from 0 to 100 (where 100 is the greatest opportunity to sell the service),
            "aiSummary": "${aiSummaryInstruction}"
          }
        ]

        Return ONLY valid JSON, without markdown code blocks and without additional text.
      `;

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
          tools: [{ googleMaps: {} }],
          temperature: 0.2,
        },
      });

      let text = response.text || "[]";
      text = text.replace(/```json/g, "").replace(/```/g, "").trim();

      let searchResults = [];
      try {
        searchResults = JSON.parse(text);
      } catch (e) {
        const match = text.match(/\[[\s\S]*\]/);
        if (match) {
          searchResults = JSON.parse(match[0]);
        } else {
          throw new Error("Invalid JSON response from Gemini");
        }
      }

      const chunks =
        response.candidates?.[0]?.groundingMetadata?.groundingChunks;
      if (chunks) {
        chunks.forEach((chunk: any) => {
          if (chunk.maps?.uri && chunk.maps?.title) {
            const matchedResult = searchResults.find(
              (r: any) =>
                r.name.toLowerCase().includes(chunk.maps.title.toLowerCase()) ||
                chunk.maps.title.toLowerCase().includes(r.name.toLowerCase()),
            );
            if (matchedResult && !matchedResult.googleMapsUri) {
              matchedResult.googleMapsUri = chunk.maps.uri;
            }
          }
        });
      }

      searchResults.sort(
        (a: any, b: any) => (b.digitalPainScore || 0) - (a.digitalPainScore || 0),
      );

      setResults(searchResults || []);
      setStep("results");
    } catch (err: any) {
      console.error("Search error:", err);
      setError(err.message || t.error.unexpected);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSelectLead = (lead: Lead) => {
    setSelectedLead(lead);
    setStep("detail");
  };

  const handleBackToSearch = () => {
    setStep("search");
    setResults([]);
    setSelectedLead(null);
  };

  const handleBackToResults = () => {
    setStep("results");
    setSelectedLead(null);
  };

  return (
    <div className="min-h-screen" style={{ backgroundColor: "var(--bg)" }}>
      {/* Aurora Mesh background — search step only */}
      {step === "search" && (
        <div className="search-bg" aria-hidden="true">
          <div className="search-bg-base" />
          <div className="search-bg-beam" />
          <div className="search-bg-orb search-bg-orb-1" />
          <div className="search-bg-orb search-bg-orb-2" />
          <div className="search-bg-orb search-bg-orb-3" />
          <div className="search-bg-orb search-bg-orb-4" />
          <div className="search-bg-spotlight" />
          <div className="search-bg-grid" />
          <div className="search-bg-vignette" />
        </div>
      )}

      {/* Header */}
      <header
        className="sticky top-0 z-20 relative"
        style={{
          backgroundColor: "rgba(255, 255, 255, 0.92)",
          backdropFilter: "blur(16px)",
          WebkitBackdropFilter: "blur(16px)",
          boxShadow: "0 1px 0 rgba(15, 23, 42, 0.05)",
        }}
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
          {/* Logo */}
          <button
            onClick={handleBackToSearch}
            className="flex items-center gap-2.5 group"
          >
            <div
              className="p-1.5 rounded-lg transition-all"
              style={{ backgroundColor: "var(--accent)" }}
            >
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <span
              className="font-bold text-lg tracking-tight"
              style={{
                fontFamily: "var(--font-display)",
                color: "var(--text)",
              }}
            >
              Prospect
              <span style={{ color: "var(--accent)" }}>AI</span>
            </span>
          </button>

          {/* Breadcrumb */}
          {step !== "search" && (
            <nav
              className="hidden sm:flex items-center gap-1.5 text-xs"
              style={{ color: "var(--text-muted)" }}
            >
              <button
                onClick={handleBackToSearch}
                className="hover:underline"
                style={{ color: undefined }}
              >
                {t.header.breadcrumb.search}
              </button>
              {(step === "results" || step === "detail") && (
                <>
                  <ChevronRight
                    className="w-3 h-3"
                    style={{ color: "var(--text-subtle)" }}
                  />
                  <button
                    onClick={handleBackToResults}
                    className="hover:underline"
                    style={{
                      color: step === "results" ? "var(--accent)" : undefined,
                    }}
                  >
                    {results.length} {t.header.breadcrumb.leads}
                  </button>
                </>
              )}
              {step === "detail" && selectedLead && (
                <>
                  <ChevronRight
                    className="w-3 h-3"
                    style={{ color: "var(--text-subtle)" }}
                  />
                  <span
                    className="max-w-[180px] truncate font-medium"
                    style={{ color: "var(--accent)" }}
                  >
                    {selectedLead.name}
                  </span>
                </>
              )}
            </nav>
          )}

          {/* Right side: Language switcher + AI status */}
          <div className="flex items-center gap-3">
            <LanguageSwitcher />
            <div
              className="hidden sm:flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-medium border"
              style={{
                backgroundColor: "var(--accent-light)",
                borderColor: "rgba(79, 70, 229, 0.15)",
                color: "var(--accent)",
              }}
            >
              <span
                className="w-1.5 h-1.5 rounded-full animate-pulse-dot"
                style={{ backgroundColor: "var(--success)" }}
              />
              {t.header.geminiActive}
            </div>
          </div>
        </div>
        {/* Gradient accent line */}
        <div style={{
          height: "1px",
          background: "linear-gradient(90deg, transparent 0%, var(--border) 15%, rgba(79,70,229,0.25) 50%, var(--border) 85%, transparent 100%)",
        }} />
      </header>

      {/* Main content */}
      <main className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        {error && (
          <div
            className="mb-6 p-4 rounded-xl flex items-center justify-between text-sm border"
            style={{
              backgroundColor: "var(--danger-bg)",
              borderColor: "var(--danger-border)",
              color: "var(--danger)",
            }}
          >
            <span>{error}</span>
            <button
              onClick={() => setError(null)}
              className="font-bold ml-4 text-lg leading-none opacity-70 hover:opacity-100 transition-opacity"
            >
              &times;
            </button>
          </div>
        )}

        {step === "search" && (
          <div className="animate-fade-up">
            <SearchForm onSearch={handleSearch} isLoading={isLoading} />
          </div>
        )}

        {step === "results" && (
          <div className="animate-fade-up">
            <ResultsList
              results={results}
              onSelectLead={handleSelectLead}
              onBack={handleBackToSearch}
            />
          </div>
        )}

        {step === "detail" && selectedLead && searchParams && (
          <div className="animate-fade-up">
            <LeadDetail
              lead={selectedLead}
              searchParams={searchParams}
              onBack={handleBackToResults}
              cachedReport={reportCache.current.get(selectedLead.id)}
              onReportGenerated={(id, report) => reportCache.current.set(id, report)}
            />
          </div>
        )}
      </main>
    </div>
  );
}
