export type Country = {
  value: string;
  label: string;
  language: "pt-BR" | "pt-PT" | "es" | "en";
  states?: { value: string; label: string }[];
};

export const COUNTRIES: Country[] = [
  {
    value: "BR",
    label: "Brasil",
    language: "pt-BR",
    states: [
      { value: "AC", label: "Acre" },
      { value: "AL", label: "Alagoas" },
      { value: "AP", label: "Amapá" },
      { value: "AM", label: "Amazonas" },
      { value: "BA", label: "Bahia" },
      { value: "CE", label: "Ceará" },
      { value: "DF", label: "Distrito Federal" },
      { value: "ES", label: "Espírito Santo" },
      { value: "GO", label: "Goiás" },
      { value: "MA", label: "Maranhão" },
      { value: "MT", label: "Mato Grosso" },
      { value: "MS", label: "Mato Grosso do Sul" },
      { value: "MG", label: "Minas Gerais" },
      { value: "PA", label: "Pará" },
      { value: "PB", label: "Paraíba" },
      { value: "PR", label: "Paraná" },
      { value: "PE", label: "Pernambuco" },
      { value: "PI", label: "Piauí" },
      { value: "RJ", label: "Rio de Janeiro" },
      { value: "RN", label: "Rio Grande do Norte" },
      { value: "RS", label: "Rio Grande do Sul" },
      { value: "RO", label: "Rondônia" },
      { value: "RR", label: "Roraima" },
      { value: "SC", label: "Santa Catarina" },
      { value: "SP", label: "São Paulo" },
      { value: "SE", label: "Sergipe" },
      { value: "TO", label: "Tocantins" },
    ],
  },
  {
    value: "PT",
    label: "Portugal",
    language: "pt-PT",
    states: [
      { value: "AV", label: "Aveiro" },
      { value: "BE", label: "Beja" },
      { value: "BR", label: "Braga" },
      { value: "BG", label: "Bragança" },
      { value: "CB", label: "Castelo Branco" },
      { value: "CO", label: "Coimbra" },
      { value: "EV", label: "Évora" },
      { value: "FA", label: "Faro" },
      { value: "GU", label: "Guarda" },
      { value: "LE", label: "Leiria" },
      { value: "LI", label: "Lisboa" },
      { value: "PT", label: "Portalegre" },
      { value: "PO", label: "Porto" },
      { value: "SA", label: "Santarém" },
      { value: "SE", label: "Setúbal" },
      { value: "VC", label: "Viana do Castelo" },
      { value: "VR", label: "Vila Real" },
      { value: "VI", label: "Viseu" },
      { value: "AC", label: "Açores" },
      { value: "MA", label: "Madeira" },
    ],
  },
  {
    value: "ES",
    label: "Espanha",
    language: "es",
    states: [
      { value: "AN", label: "Andaluzia" },
      { value: "AR", label: "Aragão" },
      { value: "AS", label: "Astúrias" },
      { value: "CN", label: "Canárias" },
      { value: "CB", label: "Cantábria" },
      { value: "CL", label: "Castela e Leão" },
      { value: "CM", label: "Castela-La Mancha" },
      { value: "CT", label: "Catalunha" },
      { value: "EX", label: "Extremadura" },
      { value: "GA", label: "Galiza" },
      { value: "IB", label: "Ilhas Baleares" },
      { value: "RI", label: "La Rioja" },
      { value: "MD", label: "Madrid" },
      { value: "MU", label: "Múrcia" },
      { value: "NA", label: "Navarra" },
      { value: "PV", label: "País Basco" },
      { value: "VC", label: "Valência" },
    ],
  },
  {
    value: "US",
    label: "Estados Unidos",
    language: "en",
    states: [
      { value: "AL", label: "Alabama" },
      { value: "AK", label: "Alaska" },
      { value: "AZ", label: "Arizona" },
      { value: "AR", label: "Arkansas" },
      { value: "CA", label: "California" },
      { value: "CO", label: "Colorado" },
      { value: "CT", label: "Connecticut" },
      { value: "DE", label: "Delaware" },
      { value: "FL", label: "Florida" },
      { value: "GA", label: "Georgia" },
      { value: "HI", label: "Hawaii" },
      { value: "ID", label: "Idaho" },
      { value: "IL", label: "Illinois" },
      { value: "IN", label: "Indiana" },
      { value: "IA", label: "Iowa" },
      { value: "KS", label: "Kansas" },
      { value: "KY", label: "Kentucky" },
      { value: "LA", label: "Louisiana" },
      { value: "ME", label: "Maine" },
      { value: "MD", label: "Maryland" },
      { value: "MA", label: "Massachusetts" },
      { value: "MI", label: "Michigan" },
      { value: "MN", label: "Minnesota" },
      { value: "MS", label: "Mississippi" },
      { value: "MO", label: "Missouri" },
      { value: "MT", label: "Montana" },
      { value: "NE", label: "Nebraska" },
      { value: "NV", label: "Nevada" },
      { value: "NH", label: "New Hampshire" },
      { value: "NJ", label: "New Jersey" },
      { value: "NM", label: "New Mexico" },
      { value: "NY", label: "New York" },
      { value: "NC", label: "North Carolina" },
      { value: "ND", label: "North Dakota" },
      { value: "OH", label: "Ohio" },
      { value: "OK", label: "Oklahoma" },
      { value: "OR", label: "Oregon" },
      { value: "PA", label: "Pennsylvania" },
      { value: "RI", label: "Rhode Island" },
      { value: "SC", label: "South Carolina" },
      { value: "SD", label: "South Dakota" },
      { value: "TN", label: "Tennessee" },
      { value: "TX", label: "Texas" },
      { value: "UT", label: "Utah" },
      { value: "VT", label: "Vermont" },
      { value: "VA", label: "Virginia" },
      { value: "WA", label: "Washington" },
      { value: "WV", label: "West Virginia" },
      { value: "WI", label: "Wisconsin" },
      { value: "WY", label: "Wyoming" },
      { value: "DC", label: "District of Columbia" },
    ],
  },
  {
    value: "MX",
    label: "México",
    language: "es",
    states: [
      { value: "AGU", label: "Aguascalientes" },
      { value: "BCN", label: "Baja California" },
      { value: "BCS", label: "Baja California Sur" },
      { value: "CAM", label: "Campeche" },
      { value: "CHP", label: "Chiapas" },
      { value: "CHH", label: "Chihuahua" },
      { value: "CMX", label: "Cidade do México" },
      { value: "COA", label: "Coahuila" },
      { value: "COL", label: "Colima" },
      { value: "DUR", label: "Durango" },
      { value: "GUA", label: "Guanajuato" },
      { value: "GRO", label: "Guerrero" },
      { value: "HID", label: "Hidalgo" },
      { value: "JAL", label: "Jalisco" },
      { value: "MEX", label: "Estado do México" },
      { value: "MIC", label: "Michoacán" },
      { value: "MOR", label: "Morelos" },
      { value: "NAY", label: "Nayarit" },
      { value: "NLE", label: "Nuevo León" },
      { value: "OAX", label: "Oaxaca" },
      { value: "PUE", label: "Puebla" },
      { value: "QUE", label: "Querétaro" },
      { value: "ROO", label: "Quintana Roo" },
      { value: "SLP", label: "San Luís Potosí" },
      { value: "SIN", label: "Sinaloa" },
      { value: "SON", label: "Sonora" },
      { value: "TAB", label: "Tabasco" },
      { value: "TAM", label: "Tamaulipas" },
      { value: "TLA", label: "Tlaxcala" },
      { value: "VER", label: "Veracruz" },
      { value: "YUC", label: "Yucatán" },
      { value: "ZAC", label: "Zacatecas" },
    ],
  },
  {
    value: "AR",
    label: "Argentina",
    language: "es",
    states: [
      { value: "C", label: "Buenos Aires (cidade)" },
      { value: "B", label: "Buenos Aires (província)" },
      { value: "K", label: "Catamarca" },
      { value: "H", label: "Chaco" },
      { value: "U", label: "Chubut" },
      { value: "X", label: "Córdoba" },
      { value: "W", label: "Corrientes" },
      { value: "E", label: "Entre Ríos" },
      { value: "P", label: "Formosa" },
      { value: "Y", label: "Jujuy" },
      { value: "L", label: "La Pampa" },
      { value: "F", label: "La Rioja" },
      { value: "M", label: "Mendoza" },
      { value: "N", label: "Misiones" },
      { value: "Q", label: "Neuquén" },
      { value: "R", label: "Río Negro" },
      { value: "A", label: "Salta" },
      { value: "J", label: "San Juan" },
      { value: "D", label: "San Luís" },
      { value: "Z", label: "Santa Cruz" },
      { value: "S", label: "Santa Fé" },
      { value: "G", label: "Santiago del Estero" },
      { value: "V", label: "Tierra del Fuego" },
      { value: "T", label: "Tucumán" },
    ],
  },
  {
    value: "CO",
    label: "Colômbia",
    language: "es",
    states: [
      { value: "AMA", label: "Amazonas" },
      { value: "ANT", label: "Antioquia" },
      { value: "ARA", label: "Arauca" },
      { value: "ATL", label: "Atlântico" },
      { value: "BOL", label: "Bolívar" },
      { value: "BOY", label: "Boyacá" },
      { value: "CAL", label: "Caldas" },
      { value: "CAQ", label: "Caquetá" },
      { value: "CAS", label: "Casanare" },
      { value: "CAU", label: "Cauca" },
      { value: "CES", label: "Cesar" },
      { value: "CHO", label: "Chocó" },
      { value: "COR", label: "Córdoba" },
      { value: "CUN", label: "Cundinamarca" },
      { value: "DC", label: "Bogotá D.C." },
      { value: "GUA", label: "Guainía" },
      { value: "GUV", label: "Guaviare" },
      { value: "HUI", label: "Huila" },
      { value: "LAG", label: "La Guajira" },
      { value: "MAG", label: "Magdalena" },
      { value: "MET", label: "Meta" },
      { value: "NAR", label: "Nariño" },
      { value: "NSA", label: "Norte de Santander" },
      { value: "PUT", label: "Putumayo" },
      { value: "QUI", label: "Quindío" },
      { value: "RIS", label: "Risaralda" },
      { value: "SAP", label: "San Andrés y Providencia" },
      { value: "SAN", label: "Santander" },
      { value: "SUC", label: "Sucre" },
      { value: "TOL", label: "Tolima" },
      { value: "VAC", label: "Valle del Cauca" },
      { value: "VAU", label: "Vaupés" },
      { value: "VID", label: "Vichada" },
    ],
  },
  { value: "CL", label: "Chile", language: "es" },
  { value: "PE", label: "Peru", language: "es" },
  { value: "UY", label: "Uruguai", language: "es" },
  { value: "PY", label: "Paraguai", language: "es" },
  { value: "EC", label: "Equador", language: "es" },
  { value: "BO", label: "Bolívia", language: "es" },
  { value: "VE", label: "Venezuela", language: "es" },
  { value: "GB", label: "Reino Unido", language: "en" },
  { value: "CA", label: "Canadá", language: "en" },
  { value: "AU", label: "Austrália", language: "en" },
];

export const BRAZILIAN_STATES = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
];
